# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.2

EAPI=8

CRATES="
"
RUST_MIN_VER=1.92

inherit cargo cmake flag-o-matic

DESCRIPTION="Slint C++ integration"
HOMEPAGE="https://slint.dev"
SRC_URI="
	https://github.com/slint-ui/slint/archive/refs/tags/v${PV}.tar.gz
		-> slint-${PV}.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://gitlab.com/api/v4/projects/32909921/packages/generic/${PN}/${PV}/slint-cpp-${PV}-crates.tar.xz
	"
fi

LICENSE="|| ( GPL-3 Slint-Royalty-free-2.0 Slint-Software-3.0 )"
# Dependent crate licenses
LICENSE+="
	0BSD AGPL-3 Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD
	Boost-1.0 CC0-1.0 CDLA-Permissive-2.0 ISC MIT MPL-2.0 UoI-NCSA
	Unicode-3.0 Unicode-DFS-2016 WTFPL-2 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

IUSE="libseat nls qt test X wayland"
REQUIRED_USE="!test? ( test )"

RDEPEND="
	qt? ( dev-qt/qtbase:6[widgets] )
	libseat? ( sys-auth/seatd )
"
DEPEND="${RDEPEND}"
BDEPEND="
	dev-build/corrosion
"

src_configure() {
	# Rust extensions are incompatible with C/C++ LTO compiler see e.g.
	# https://bugs.gentoo.org/910220
	filter-lto

	local mycmakeargs=(
		-DSLINT_BUILD_EXAMPLES=OFF
		-DSLINT_BUILD_TESTING=$(usex test)
		-DSLINT_FEATURE_ACCESSIBILITY=ON

		-DSLINT_FEATURE_GETTEXT=$(usex nls)

		# https://docs.slint.dev/latest/docs/slint/guide/backends-and-renderers/backends_and_renderers/
		-DSLINT_FEATURE_BACKEND_QT=$(usex qt)
		-DSLINT_FEATURE_RENDERER_SOFTWARE=ON
		-DSLINT_FEATURE_BACKEND_WINIT=ON
		-DSLINT_FEATURE_BACKEND_WINIT_X11=$(usex X)
		-DSLINT_FEATURE_BACKEND_WINIT_WAYLAND=$(usex wayland)
		-DSLINT_FEATURE_BACKEND_LINUXKMS=$(usex kms)
		-DSLINT_FEATURE_BACKEND_LINUXKMS_NOSEAT=$(usex !libseat)
		-DSLINT_FEATURE_RENDERER_SKIA=OFF
		-DSLINT_FEATURE_RENDERER_SKIA_OPENGL=OFF
		-DSLINT_FEATURE_RENDERER_SKIA_VULKAN=OFF
		-DSLINT_FEATURE_RENDERER_FEMTOVG=ON
		-DSLINT_FEATURE_RENDERER_FEMTOVG_WGPU=ON
	)

	cmake_src_configure
}
